steps:
  - label: 'Build'
    command: 'make build'
    artifact_paths: "target/*"

  - wait

  - label: 'Docker image build & push'
    command: 'make package'
    branches: 'master develop deploy/*'

  - wait

  - label: 'Deploy to Staging'
    command: 'make deploy-cex-staging'
    branches: 'master develop deploy/*'
