steps:
  - label: 'Build'
    command: 'make build'
    artifact_paths: "target/*"

  - wait

  - label: 'Docker image build & push'
    command: 'make package'
    branches: 'master develop deploy/*'

  - wait

  - label: 'Deploy to Staging'
    command: 'make deploy-staging'
    branches: 'master develop deploy/*'

  - block: 'Request Release'
    branches: 'master'
    fields:
      - text: 'Code Name'
        key: 'release-name'
        hint: 'What’s the purpose for this release? :rocket:'
        required: false

  - label: 'Deploy to Production'
    command: 'make deploy-production'
    branches: 'master'
