export const APP_NAME     = process.env.APP_NAME || "u-skeleton"
export const COMMIT       = process.env.COMMIT || "u-commit"
export const ENVIRONMENT  = process.env.ENVIRONMENT || "u-env"
export const PROJECT      = process.env.PROJECT  || "u-project"
export const PORT         = process.env.PORT  || "8080"
export const VERSION      = process.env.VERSION  || "u-version"
